name: Comprobar Precio de Producto

on:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches:
      - main

jobs:
  check_price_job:
    runs-on: ubuntu-latest
    
    
    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt
        python -m playwright install

    - name: Ejecutar script Python
      env:
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        EMAIL_API: ${{ secrets.EMAIL_API }}
      run: |
        for i in 1 2 3 4 5 6; do
          python main.py && break || sleep 5
        done
